# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signallight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signallight',
            name='current_position',
        ),
        migrations.AddField(
            model_name='signallight',
            name='direction_pin',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='signallight',
            name='step_pin',
            field=models.IntegerField(default=12),
        ),
    ]
