# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signallight', '0002_auto_20161030_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signallight',
        ),
    ]
